### ISSUE TITLE
Editor interface `sidebar` property unexpectedly `nil`

### ISSUE THREAD

**Issue by paulstraw** [contentful/contentful-management.rb#240] opened 2022-05-20 21:24 UTC
Whenever I call `environment.editor_interfaces.default('someContentTypeId')`, I get back a `Contentful::Management::EditorInterface` with a `nil` value for the `sidebar` property. `controls` works fine, being an empty array if no fields are present, or an array with the expected values otherwise.

This is happening on contentful-management 3.4.0, Ruby 2.7.5. I've included some `rails c` output showing the issue. Note the `@properties={:controls=>[], :sidebar=>nil}` in the last editor_interface. Note that _unlike_ #229, `sidebar` is _not_ present in the `editor_interface.raw_object`.

```
myapp:development(main):002:0> client = Contentful::Management::Client.new(ENV['CONTENTFUL_MANAGEMENT_ACCESS_TOKEN'])
=> #<Contentful::Management::Client:0x0000000113eb9358 @configuration={:api_url=>"api.contentful.com...

myapp:development(main):003:0> environment = client.environments(ENV['CONTENTFUL_SPACE_ID']).find(ENV['CONTENTFUL_ENV'])
=> #<Contentful::Management::Environment: @properties={:name=>"gifgif"} @sys={:type=>"Environment", ...

myapp:development(main):004:0> test_ct = environment.content_types.create(name: 'Test CT', id: 'testCt
')
=> #<Contentful::Management::ContentType: @properties={:name=>"Test CT", :description=>nil, :fields=...

myapp:development(main):005:0> test_ct.publish # can't get editor interface until published
=> #<Contentful::Management::ContentType: @properties={:name=>"Test CT", :description=>nil, :fields=>[], :displayField=>nil} @sys={:space=>#<Contentful::Management::Link: @sys={:type=>"Link", :linkType=>"Space", :id=>"rs1lfk02rnxw"}>, :id=>"testCt", :type=>"ContentType", :createdAt=>Fri, 20 May 2022 21:13:36 +0000, :updatedAt=>Fri, 20 May 2022 21:13:41 +0000, :environment=>#<Contentful::Management::Link: @sys={:id=>"gifgif", :type=>"Link", :linkType=>"Environment"}>, :createdBy=>#<Contentful::Management::Link: @sys={:type=>"Link", :linkType=>"User", :id=>"5GrvkcrzKqUZxuZ8llCuCi"}>, :updatedBy=>#<Contentful::Management::Link: @sys={:type=>"Link", :linkType=>"User", :id=>"5GrvkcrzKqUZxuZ8llCuCi"}>, :publishedCounter=>1, :version=>2, :firstPublishedAt=>"2022-05-20T21:13:41.518Z", :publishedAt=>Fri, 20 May 2022 21:13:41 +0000, :publishedBy=>#<Contentful::Management::Link: @sys={:type=>"Link", :linkType=>"User", :id=>"5GrvkcrzKqUZxuZ8llCuCi"}>, :publishedVersion=>1, :locale=>nil}>

myapp:development(main):006:0> editor_interface = environment.editor_interfaces.default('testCt')
=> #<Contentful::Management::EditorInterface: @properties={:controls=>[], :sidebar=>nil} @sys={:id=>"default", :type=>"EditorInterface", :space=>#<Contentful::Management::Link: @sys={:id=>"rs1lfk02rnxw", :type=>"Link", :linkType=>"Space"}>, :version=>1, :createdAt=>Fri, 20 May 2022 21:13:41 +0000, :createdBy=>#<Contentful::Management::Link: @sys={:id=>"5GrvkcrzKqUZxuZ8llCuCi", :type=>"Link", :linkType=>"User"}>, :updatedAt=>Fri, 20 May 2022 21:13:41 +0000, :updatedBy=>#<Contentful::Management::Link: @sys={:id=>"5GrvkcrzKqUZxuZ8llCuCi", :type=>"Link", :linkType=>"User"}>, :contentType=>#<Contentful::Management::Link: @sys={:id=>"testCt", :type=>"Link", :linkType=>"ContentType"}>, :environment=>#<Contentful::Management::Link: @sys={:id=>"gifgif", :type=>"Link", :linkType=>"Environment"}>}>

myapp:development(main):027:0> editor_interface.raw_object
=> {"sys"=>{"id"=>"default", "type"=>"EditorInterface", "space"=>{"sys"=>{"id"=>"rs1lfk02rnxw", "type"=>"Link", "linkType"=>"Space"}}, "version"=>1, "createdAt"=>"2022-05-20T22:05:50.014Z", "createdBy"=>{"sys"=>{"id"=>"5GrvkcrzKqUZxuZ8llCuCi", "type"=>"Link", "linkType"=>"User"}}, "updatedAt"=>"2022-05-20T22:05:50.014Z", "updatedBy"=>{"sys"=>{"id"=>"5GrvkcrzKqUZxuZ8llCuCi", "type"=>"Link", "linkType"=>"User"}}, "contentType"=>{"sys"=>{"id"=>"testCt", "type"=>"Link", "linkType"=>"ContentType"}}, "environment"=>{"sys"=>{"id"=>"gifgif", "type"=>"Link", "linkType"=>"Environment"}}}, "controls"=>[]}
```

If you visit the Contentful GUI, you can see that the content type does actually have sidebar widgets enabled:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/117288/169612156-c2dbe937-c112-441f-950b-bba250a6bf22.png">

**Comment by rubydog** [comment] 2022-05-29 18:23
@paulstraw Did downgrading fix the issue?

**Comment by paulstraw** [comment] 2022-05-31 17:34
@rubydog downgrading to the last release before the sidebar feature was added works for us as a temporary fix, yes. Of course, now we don't have access to edit the sidebar if needed.

**Comment by rubydog** [comment] 2022-06-27 12:44
@paulstraw It will only return sidebar if there has been changes to sidebar. I will close this issue for now as it is not a bug in contentful-management.rb but feel free to re-open it if you have any doubts.

Cheers

**Closed by rubydog** 2022-06-27 12:44 UTC
