### ISSUE TITLE
fields_for_query has buggy order-dependent logic

### ISSUE THREAD

**Issue by grncdr** [contentful/contentful-management.rb#70] opened 2015-11-12 09:14 UTC
This comes from ZenDesk, and appears to be a bug on [this line](https://github.com/contentful/contentful-management.rb/blob/fcadb13e8096a75c7dd7d1e959023d310c0af55e/lib/contentful/management/entry.rb#L195).

If the first `(locale, fields)` tuple in `raw_fields` does not contain every field name, then the result of `fields_for_query` can entirely skip fields that _do_ have defined values in other locales.

**Comment by dlitvakb** [comment] 2015-11-12 16:36
@grncdr after several tests, I cannot find any unexpected behaviour related to the pointed out method or any `*_with_locales` field

### Tests done:

On a Space with 2 locales with 1 content type, with fields `a` (localized), `b` (not localized), created entries like the following (On the UI, then queried with the SDK):

- `{a: {'en-US': 'foo', 'es': 'bar'}, b: nil}`

> Calling `entry.a_with_locales` returned: `{'en-US': 'foo', 'es': 'bar'}`
> Calling `entry.a` returned: `'foo'`

- `{a: {'en-US': nil, 'es': 'bar'}, b: nil}`

> Calling `entry.a_with_locales` returned: `{'en-US': nil, 'es': 'bar'}`
> Calling `entry.a` returned: `nil`

- `{a: nil, b: 'foobar'}`

> Calling `entry.b_with_locales` returned: `{'en-US': 'foobar', 'es': nil}`
> Calling `entry.a` returned: `'foobar'`

All of these were the expected results.

Closing, until more information is provided

**Comment by lluzak** [comment] 2015-11-13 07:08
Hey, @dlitvakb, all tests above are correct, but what we are getting from API is:

```
{
  "fields": {
    "nameIntern": {
      "no-NO": "Animal School Day",
      "dk-DK": "Animal School Day",
      "pl-PL": "Animal School Day",
      "en-US": "Animal School Day",
      "de-DE": "Ein tierischer Schultag",
      "de-AT": "Ein tierischer Schultag",
      "de-CH": "Ein tierischer Schultag",
      "se-SE": "Animal School Day",
      "nl-BE": "Dierenschooldag",
      "nl-NL": "Dierenschooldag"
    },
     "iOsPhoneId": {
      "en-US": "588812258"
    },
    "iOsTabletId": {
      "en-US": "588813273"
    }
}
```

Because of wrong order of locales in fields ( other entries always have ``en-US`` locale as first ), when i call:
```ruby
entry.i_os_phone_id // "588812258"
entry.i_os_phone_id_with_locales // nil
```

Problem is in https://github.com/contentful/contentful-management.rb/blob/master/lib/contentful/management/entry.rb#L195, where is assume that default locale in ```@fields``` is always first.

My ```@fields``` variable looks like:
```ruby
{
  "no-NO" =>  {
    "nameIntern" => "Animal School Day"
  },
  "en-US" => {
    "nameIntern" => "Animal School Day",
    "iOsPhoneId" => "...",
    "iOsTabletId" => "..."
  }
}
```

**Comment by grncdr** [comment] 2015-11-13 09:05
Thanks for providing these extra details @lluzak! AFAIK the ordering of keys in JSON objects (and Ruby hashes) is not something one can depend on, so if the code does that's probably a mistake, and @dlitvakb was just lucky with his tests.

**Comment by dlitvakb** [comment] 2015-11-13 11:11
@lluzak Oh, the issue makes sense now. Have actually no idea how to generate it so that the default locale is not the first place, but, I got to fix the issue by merging whatever is there from any locale.

PR soon

**Closed** 2015-11-24 13:09 UTC
Labels: bug
