### ISSUE TITLE
Localization: default locale returned for empty fields without fallback

### ISSUE THREAD

**Issue by mxlje** [contentful/contentful-management.rb#164] opened 2018-06-13 10:08 UTC
I have the following code:

```ruby
entry = environment.entries.find('ENTRY_ID')

puts entry.title # prints English title
entry.locale = 'de'
puts entry.title # prints German title
```

So far so good.

But when I change `locale=` to another locale code that exists in my space, for which no fallback locale has been specified and for which the entry in question has no value saved (the field is empty), it returns content in the default locale (English in this case). The same is true for literally any other string I set as `locale=` on the entry object.

```ruby
entry.locale = 'ru' # doesn’t exist in my space
puts entry.title # prints English title

entry.locale = 'literally anything'
puts entry.title # prints English title
```

What am I missing here? I would expect an empty string to be returned. Is there a different way I should be querying for different locales? I am using the management API and not `contentful.rb` because the goal is to later on update the entries, but with no way of checking if a field is empty in a given locale that becomes very error prone.

Thank you for any pointers.

**Comment by dlitvakb** [comment] 2018-06-13 11:03
Hey @mxlje and @anjawaldbauer,

Let me investigate this a little bit and I'll let you know as soon as I find out more about this.

Cheers

**Comment by dlitvakb** [comment] 2018-06-13 11:45
I reproduced the case and examined our code and tests, and it turns out that since the SDK was created there were assumptions in place that when a field is not found for the locale the default locale value should be presented instead. This is only the case for reading, for writing it uses whatever there is present in the locale, and doesn't include other values. This behaviour predates the existence of fallback locales in the API, and I mainly think that's the reason it has been like that. And as this issue never arose, I never really thought too much about it.

I've just discussed with my team about what the correct way of dealing this would be, and we've agreed that removing this assumption and have the SDK return `nil` when there's no value for that field is the proper handling that should be done.

Therefore, I'm going to create a PR to remove this fallback behaviour. But that said, as this is a breaking change, I'm going to hold creating a major release until more features are added. In the meantime, after the PR is merged, you should be able to work with the `master` branch, as it is stable.

Hope this helps,

Cheers

**Comment by mxlje** [comment] 2018-06-13 12:28
Hey @dlitvakb, thank you for your fast reply. Your explanation makes total sense and is what I assumed might have happened.

I just installed this gem from your feature branch and it now correctly returns nil 🎉 

Thank you for the quick resolution. I’ll use it from master (when it is merged) and will switch to the release version once it is out.

**Closed** 2018-06-13 12:28 UTC

**Comment by dlitvakb** [comment] 2018-06-13 12:38
Hey @mxlje,

This has now been merged,

Cheers
